# Generated by Django 2.2.20 on 2021-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20211122_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=4)),
                ('departure_station', models.CharField(max_length=1)),
                ('arrival_station', models.CharField(max_length=1)),
                ('departure_time', models.BigIntegerField(max_length=5)),
                ('arrival_time', models.BigIntegerField(max_length=5)),
                ('cost', models.IntegerField(max_length=5)),
            ],
        ),
    ]
