# Generated by Django 2.2.20 on 2021-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_trains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=4)),
                ('departure_station', models.CharField(max_length=1)),
                ('arrival_station', models.CharField(max_length=1)),
                ('departure_time', models.BigIntegerField()),
                ('arrival_time', models.BigIntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Trains',
        ),
    ]
