# Generated by Django 2.2.20 on 2021-11-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
