# Generated by Django 2.2.20 on 2021-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=100)),
                ('train_id', models.CharField(max_length=6)),
                ('boarding_station', models.CharField(max_length=1)),
                ('arrival_station', models.CharField(max_length=1)),
                ('board_time', models.BigIntegerField()),
                ('arrive_time', models.BigIntegerField()),
                ('seats_booked', models.IntegerField()),
                ('total_cost', models.BigIntegerField()),
                ('pnr', models.CharField(max_length=106)),
            ],
        ),
    ]
