# Generated by Django 2.2.20 on 2021-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20211125_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.BigIntegerField(),
        ),
    ]
