# Generated by Django 2.2.20 on 2021-11-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20211125_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrive_time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='board_time',
            field=models.CharField(max_length=6),
        ),
    ]
