# Generated by Django 2.2.20 on 2021-11-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20211125_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
