# Generated by Django 2.2.20 on 2021-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_id',
            field=models.CharField(max_length=6),
        ),
    ]
