# Generated by Django 2.2.20 on 2021-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_auto_20211125_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrive_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='board_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrive_dt',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='board_dt',
            field=models.CharField(default='', max_length=25),
        ),
    ]
