# Generated by Django 2.2.20 on 2021-11-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_auto_20211126_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to', models.CharField(max_length=100)),
                ('train_id', models.CharField(max_length=6)),
                ('departure', models.CharField(default='', max_length=25)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
    ]
