# Generated by Django 2.2.20 on 2021-11-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='seats',
            new_name='capacity',
        ),
    ]
