# Generated by Django 2.2.20 on 2021-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_auto_20211126_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='belongs_to',
        ),
    ]
