# Generated by Django 2.2.20 on 2021-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0017_remove_seats_belongs_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seats',
        ),
        migrations.AddField(
            model_name='train',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
