# Generated by Django 2.2.20 on 2021-11-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20211126_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='capacity',
        ),
    ]
