# Generated by Django 2.2.20 on 2021-11-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0020_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
