# Generated by Django 2.2.20 on 2021-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0021_delete_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=6)),
                ('DepartureDate', models.CharField(max_length=10)),
                ('current_capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
