# Generated by Django 2.2.20 on 2021-11-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0022_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_nums',
            field=models.CharField(default='', max_length=100),
        ),
    ]
