# Generated by Django 2.2.20 on 2021-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_booking_seat_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=6)),
                ('departure_station', models.CharField(max_length=1)),
                ('arrival_station', models.CharField(max_length=1)),
                ('departure_date', models.CharField(max_length=100)),
                ('arrival_date', models.CharField(max_length=100)),
                ('booked_seats', models.CharField(max_length=1000)),
                ('all_seats', models.CharField(max_length=1000)),
            ],
        ),
    ]
