# Generated by Django 2.2.20 on 2021-11-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_trainseats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainSeats',
            new_name='TrainSeat',
        ),
    ]
