# Generated by Django 2.2.20 on 2021-11-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0026_train_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='train_status',
            new_name='TrainStatus',
        ),
    ]
