# Generated by Django 2.2.20 on 2021-11-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0027_auto_20211127_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
